Added database file to admission_rules.d
nikosT/regale-nixos-compose pull request #1
Opened 2023-10-06 00:24 UTC by stratos-karas

2023-10-07 21:22 UTC, nikosT requested changes

2023-10-07 21:22 UTC, nikosT commented on oar-iccs/common_config.nix
>        cp etc/oar/admission_rules.d/trainedGradientBoostingRegressor.model $out/admission_rules.d
better add && at the end

2023-10-07 21:22 UTC, nikosT commented on oar-iccs/setup.toml
remove file from pr

2023-10-08 12:42 UTC, stratos-karas commented on oar-iccs/common_config.nix
>        cp etc/oar/admission_rules.d/trainedGradientBoostingRegressor.model $out/admission_rules.d
Added

2023-10-08 12:43 UTC, stratos-karas commented on oar-iccs/setup.toml
Added &&

2023-10-08 19:45 UTC, nikosT approved these changes
good to go

2023-10-08 19:45 UTC, merged